### ISSUE TITLE
it saids [16528] failed to execute script main

### ISSUE THREAD

**Issue by raykingmine** [deep-man-yy/pepenude#10]
I have installed all the required software, but it won't render

**Comment by MatthewHKnight** [comment]
That's because @Deep-man-yy shut down his server that is used to process the images, which is freaking dumb why even need a GPU or CPU if the stuff has to be passed over to a server for processing it.
I don't get why he hasn't released the stuff for server-side yet.

**Comment by deep-man-yy** [comment]
> I have installed all the required software, but it won't render

Open the DevTools (View > Toggle DevTools) and upload a photo of what you see in the "Console Tab"

> That's because @deep-man-yy shut down his server that is used to process the images, which is freaking dumb why even need a GPU or CPU if the stuff has to be passed over to a server for processing it.
> I don't get why he hasn't released the stuff for server-side yet.
> From what I heard to this program only works on Windows 10.

I have answered your issue indicating that you have been confused, that is not how the program works.

**Comment by MatthewHKnight** [comment]
> > I have installed all the required software, but it won't render
> 
> Open the DevTools (View > Toggle DevTools) and upload a photo of what you see in the "Console Tab"
> 
> > That's because @deep-man-yy shut down his server that is used to process the images, which is freaking dumb why even need a GPU or CPU if the stuff has to be passed over to a server for processing it.
> > I don't get why he hasn't released the stuff for server-side yet.
> > From what I heard to this program only works on Windows 10.
> 
> I have answered your issue indicating that you have been confused, that is not how the program works.

Yes, I am very aware of that as I said I didn't want to install Wireshark or I would've figured that out, I did install Wireshark and found out myself why it was trying to open a port on the firewall.

As I mentioned in that closed issue you did PriateBay has a much stable version and less of a problem, for idiots to use ex; My virgin friends.

**Comment by wisp101** [comment]
@deep-man-yy Actually I was looking at the code and I was wondering the same thing. Why DO you use a local http server? Is it a limitation of nuxt.js or something?

**Comment by deep-man-yy** [comment]
> @deep-man-yy Actually I was looking at the code and I was wondering the same thing. Why DO you use a local http server? Is it a limitation of nuxt.js or something?

It is not a limitation, the local server is only destined for development/test or when you want to use NuxtJS as SSR. NuxtJS has the option to compile the project to static content to avoid having to create a local server, the only problem is that the static content is generated thinking that you are going to place it in a shared Hosting in the root folder of your site, when trying to use it in Electron the site will try to load the resources from the root of the device where it is installed, something like `C:\_ nuxt\assets\app.js`

As it is the first version and it is an alpha I decided to just leave the local server and in future versions solve that problem and no longer need that

**Comment by wisp101** [comment]
I see. Maybe adding a warning or something to the Readme would be nice so people don't get scared by their firewall and make sure nothing else is running on the required port.

**Comment by seravifer** [comment]
I am having this trace of error.
```
stderr: [8848] Failed to execute script main
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "c:\tools\anaconda3\envs\edp\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\cv2\__init__.py", line 3, in <module>
ImportError: DLL load failed: The specified module could not be found.
```

Why is the file path absolute?

**Comment by deep-man-yy** [comment]
@seravifer **If you are compiling the project yourself,** it should not be like that, unless you use Anaconda and that's where you have the packages.

**If you are using the binaries already compiled,** the path is absolute because that was the location on my computer at the time of compiling and packaging everything, it is only for reference and **should not affect anything**, the error "DLL load failed" means that your installation is corrupt or that your Windows needs components to run the program.
