### ISSUE TITLE
Online version

### ISSUE THREAD

**Issue by mssc89** [deep-man-yy/pepenude#12]
Hi!
I've created an online version of this tool, android app is on its way. It would be great to hear from you, please check out http://deepnudeonline.com

Its still a beta, a few things to fix and improve, but i hope for a prod release in a few days.

**Comment by deeppppp** [comment]
Nice :)
I have few suggestions:
- Please link the Discord / Telegram community areas. Getting more people on those the better the project will be.
- In the output image where there is a preview and [Save] button, the image needs to be size 512px by 512px in the preview window.. Right now the image size is stretched across the browser window, giving it a bad appearance.
- A telegram and discord bot that does the same, input image, output result image would be great to drive people to the community areas as well. Perhaps something that you want to address after the web version is done?

**Comment by dbof10** [comment]
Is this the original DeepNude?

**Comment by deeppppp** [comment]
This is a fork from the original DeepNude.

"In software engineering, a project fork happens when developers take a copy of source code from one software package and start independent development on it, creating a distinct and separate piece of software."

**Comment by deep-man-yy** [comment]
The site works and even if you are not using the CLI version of PepeNude that would not matter if you were not trying to get income with an XMR Miner. Please look for another way to generate income for your project if you want to advertise in this repository.

![](https://i.imgur.com/yiAjXqq.png)
