### ISSUE TITLE
TypeError: Cannot read property 'isValidPhoto' of undefined

### ISSUE THREAD

**Issue by ifrontend-xyz** [deep-man-yy/pepenude#14]
TypeError: Cannot read property 'isValidPhoto' of undefined

**Comment by deeppppp** [comment]
can you provide a bit more context; i.e. are you using the CLI or GUI?
are you using the Developer src or the binaries?

The issue maybe that the input image is not 512px by 512px - a requirement that the GUI enforces, but not the CLI at this time.

**Comment by ifrontend-xyz** [comment]
i use gui and yarn install && npm run dev

**Comment by deeppppp** [comment]
do you have the same issue if you use the CLI interface? Can you supply the full error message; i.e. is there a call stack part of the error output?

**Comment by ifrontend-xyz** [comment]
![1562814534556](https://user-images.githubusercontent.com/1844777/61019322-5cf92b00-a3cc-11e9-8310-90f0ed24172d.jpg)

**Comment by deep-man-yy** [comment]
@ifrontend-xyz The interface does not work if it is loaded from a normal web browser, to make it work you need to run `yarn dev-gui` to start the GUI.

**Comment by ifrontend-xyz** [comment]
thanks
