### ISSUE TITLE
Multiple errors

### ISSUE THREAD

**Issue by capmalo** [deep-man-yy/pepenude#19]
Hi ! I have multiple errors with the GUI version, CPU or GPU. What is the problem ?
![image](https://user-images.githubusercontent.com/12106464/61071413-50e38c80-a411-11e9-850a-8dc3f21d7bcd.png)

**Comment by nimeshvaghasiya** [comment]
@capmalo  I had same issue, is it fixed?

**Comment by wisp101** [comment]
You probably set up the application incorrectly; The cli failed to start.
