### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by deep-man-yy** [deep-man-yy/pepenude#20]
Right now it seems that the application is only compatible with Windows 10. If you use Windows 7 and PepeNude works properly, please let me know.

**Comment by PommeDroid** [comment]
Can confirm that the freeze version of the cli from the drive doesn't work directly on windows 7. Got an "Import error : DLL loaded failed" when launching cli.exe . But I'm able to run it without a problem by installing manually all python dependencies... 
Maybe you need to freeze the program with pyinstaller for windows 7 on windows 7???

**Comment by PommeDroid** [comment]
From the pyisntaller documentation https://pyinstaller.readthedocs.io/en/stable/usage.html#windows :

For Python >= 3.5 targeting Windows < 10, the developer needs to take special care to include the Visual C++ run-time .dlls: Python 3.5 uses Visual Studio 2015 run-time, which has been renamed into “Universal CRT“ and has become part of Windows 10. For Windows Vista through Windows 8.1 there are Windows Update packages, which may or may not be installed in the target-system. So you have the following options:

    Build on Windows 7 which has been reported to work.

    Include one of the VCRedist packages (the redistributable package files) into your application’s installer. This is Microsoft’s recommended way, see “Distributing Software that uses the Universal CRT“ in the above-mentioned link, numbers 2 and 3.

    Install the Windows Software Development Kit (SDK) for Windows 10 and expand the .spec-file to include the required DLLs, see “Distributing Software that uses the Universal CRT“ in the above-mentioned link, number 6.

    If you think, PyInstaller should do this by itself, please help improving PyInstaller.
