### ISSUE TITLE
Peppernude fails to transform image on Arch Linux

### ISSUE THREAD

**Issue by hielQ91** [deep-man-yy/pepenude#22]
When i try to transform the image on the CPU i get this error
![Screenshot from 2019-07-12 15-03-29](https://user-images.githubusercontent.com/51532468/61130307-acb42100-a4b6-11e9-866d-9a7c996c2ca3.png)

**Comment by hielQ91** [comment]
It could be a problem with Python 3.7.3 so i will downgrade it and test it again

**Comment by hielQ91** [comment]
On python 3.7.1 it does not work either.

**Comment by hielQ91** [comment]
CLI gives the same error

**Comment by wisp101** [comment]
Did you download the CLI checkpoints?

**Comment by hielQ91** [comment]
Yes i did download the CLI checkpoints.

**Comment by hielQ91** [comment]
It was a permission issue with one of the packages on my side
