### ISSUE TITLE
canary build issues

### ISSUE THREAD

**Issue by deeppppp** [deep-man-yy/pepenude#23]
CLI works OK

When cropping the image, the user can also ZOOM in or out, via mouse scroll wheel.
Can this be mentioned in the instructions pane 'Photo cropping'?

The result preview does not show the image.

The [save] function writes a text file to disk with the string 'undefined' instead of a result image.

[open directory] throws an error message:
Windows cannot find
<user path>\AppData\Roaming\pepenude-gui\models\Uncategorized

**Comment by deeppppp** [comment]
"To solve it manually you must go to the folder: %USERPROFILE%\AppData\Roaming\ pepenude-gui (This folder is created once you have opened the GUI for the first time) and create inside the folder models and within it create another folder called Uncategorized"

fixed the result preview not showing
fixed the save function not working
fixed the open directory not working

----

Bug that was carried over:
if the cropping function is used in the GUI; i.e. the input image is not 512x512 then the output image is reduced in quality

**Comment by wisp101** [comment]
[This](https://github.com/fengyuanchen/cropperjs/issues/145) issue in cropperjs probably has the solution. I think we are exporting the image in lower quality since that is the default option.
