### ISSUE TITLE
Build from src issues encountered and solutions

### ISSUE THREAD

**Issue by deeppppp** [deep-man-yy/pepenude#3]
Following the instructions (issuing the install.bat and then build.bat commands from easydeepnude-master\src)
Only the easydeepnude-master\dist\cli\ build succeeded.

----
I suggest putting in the README.md that the checkpoints directory with the data files is still required to make either CLI or GUI build from src to function.
---

The GUI didn't build
Here are the issues I encountered; after issuing the 'yarn build' command in the easydeepnude-master\src\gui\ directory I encountered this error:

$ cross-env NODE_ENV=PRODUCTION electron-builder
'cross-env' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.

Solved it by running:
npm install cross-env

Then the following issue:
$ cross-env NODE_ENV=PRODUCTION electron-builder
'electron-builder' is not recognized as an internal or external command,
operable program or batch file.
events.js:174
      throw er; // Unhandled 'error' event

Solved it by running:
npm install electron-builder

Then the following issue:
Error: Unresolved node modules: @nuxtjs/axios, @nuxtjs/pwa, @nuxtjs/dotenv, cropperjs, image-to-base64, js-event-bus, mime-types, nuxt, clipboard, debug, downloadjs, lodash, md5, moment, queue, randomcolor, supports-color, sweetalert, tippy.js, uuid

Solved it by running the 'yarn install' command - I recon the install.bat that was run before failed the 'yarn install' part because the previous issues.

After that I issued:
'yarn build'

and the gui build succeeded and placed the build in:
easydeepnude-master\dist\gui

**Comment by wisp101** [comment]
Strange. The provided build and install scripts worked nearly flawlessly for me.
