### ISSUE TITLE
Can you make a linux version of this ?

### ISSUE THREAD

**Issue by Doctopus18** [deep-man-yy/pepenude#5]
a version that we could launch with python for example, it would be possible ? Then it can also works with MacOS

Thanks in advance for your answer :)

**Comment by wisp101** [comment]
Well all the code is python and electron, so shouldn't it already work on Linux?

**Comment by Doctopus18** [comment]
> Well all the code is python and electron, so shouldn't it already work on Linux?

So, which file i have ton launch ?

**Comment by MatthewHKnight** [comment]
LMAOOOOOOOOOOOOOOOOOOOO You gotta be fucking kidding me.
Make it work with Linux brah this shit works fine with Linux if you know how to use linux.
Take a screen shot once I have Ubuntu 16.04.6 downloaded I'll make a video how on to install it for all the people with autism as well.

**Comment by wisp101** [comment]
@MatthewHKnight For the love of all that is good and holy in this world, please don't run this in wine
@Doctopus18 Taking a quick look, the build scripts can be easily converted to work on Linux. I'll try to drop a working script here when I get it working

**Comment by wisp101** [comment]
I converted the build scripts, but some other problems came up. **It does not work yet.** It won't convert things, but i managed to get a window open. I'll probably finish this tomorrow. Not sure if this is a good idea or not, but maybe writing these scripts in js or python is a good idea to make them cross platform. Then again, these are reasonably simple i guess.

### src/install.sh
```
#!/bin/bash

# Notes:
# * Needs Nodejs (Haven't tested minimum version, I used version 12.6.0)
# * Needs Yarn (Haven't tested minimum version, I used 1.16.0)
# * Needs Python3 (3.5 for current Torch dep)
# * Needs pip3 (Haven't tested minimum version, I used 9.0.1)
# * Torch needs Python Version 3.5 and Cuda Version 10
# * Python and cuda requirements can be changed by tinkering with the Torch deps
# * I built this on x64. Edit the Torch deps for other platforms
# * I didn't version lock dependencies so if stuff doesn't work install the correct version

cd cli

# NOTE: Make sure pyinstaller is accessible from the cmdline as "pyinstaller".
# Otherwise, track down its folder and add it to your path. I found mine in "~/.local/bin".

pip3 install numpy opencv-python rsa pyinstaller

# Edit these for your platform/python-version/cuda-config:
pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp35-cp35m-linux_x86_64.whl
pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp35-cp35m-linux_x86_64.whl 

cd ../gui
yarn install

echo "Installation completed, now you can edit the code and compile the project with build.sh"
```

### src/build.sh
```
#!/bin/bash

cd cli
pyinstaller main.py -y --onedir --name "cli" --distpath "../../dist"


cd ../gui
yarn build

# Notes: 
# * May need to make "chrome-engine" in dist owned by root
# * May need to give "chrome-sandbox" 4755 permissions
```

### Result
![image](https://user-images.githubusercontent.com/52584690/60866919-7472c100-a1de-11e9-9c53-21d16165d5e4.png)

**Comment by wisp101** [comment]
@Doctopus18 Well I 'm brain dead I just realized you said Mac Os and not Linux. I don't have a Mac so I can't test anything, but I think the scripts should still work on Mac. If you could test them out that would be great.

**Comment by Doctopus18** [comment]
> I converted the build scripts, but some other problems came up. **It does not work yet.** It won't convert things, but i managed to get a window open. I'll probably finish this tomorrow. Not sure if this is a good idea or not, but maybe writing these scripts in js or python is a good idea to make them cross platform. Then again, these are reasonably simple i guess.
> 
> ### src/install.sh
> ```
> #!/bin/bash
> 
> # Notes:
> # * Needs Nodejs (Haven't tested minimum version, I used version 12.6.0)
> # * Needs Yarn (Haven't tested minimum version, I used 1.16.0)
> # * Needs Python3 (3.5 for current Torch dep)
> # * Needs pip3 (Haven't tested minimum version, I used 9.0.1)
> # * Torch needs Python Version 3.5 and Cuda Version 10
> # * Python and cuda requirements can be changed by tinkering with the Torch deps
> # * I built this on x64. Edit the Torch deps for other platforms
> # * I didn't version lock dependencies so if stuff doesn't work install the correct version
> 
> cd cli
> 
> # NOTE: Make sure pyinstaller is accessible from the cmdline as "pyinstaller".
> # Otherwise, track down its folder and add it to your path. I found mine in "~/.local/bin".
> 
> pip3 install numpy opencv-python rsa pyinstaller
> 
> # Edit these for your platform/python-version/cuda-config:
> pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp35-cp35m-linux_x86_64.whl
> pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp35-cp35m-linux_x86_64.whl 
> 
> cd ../gui
> yarn install
> 
> echo "Installation completed, now you can edit the code and compile the project with build.sh"
> ```
> 
> ### src/build.sh
> ```
> #!/bin/bash
> 
> cd cli
> pyinstaller main.py -y --onedir --name "cli" --distpath "../../dist"
> 
> 
> cd ../gui
> yarn build
> 
> # Notes: 
> # * May need to make "chrome-engine" in dist owned by root
> # * May need to give "chrome-sandbox" 4755 permissions
> ```
> 
> ### Result
> ![image](https://user-images.githubusercontent.com/52584690/60866919-7472c100-a1de-11e9-9c53-21d16165d5e4.png)

that's great ! it would be very cool if you could create a script that works totally :)

**Comment by wisp101** [comment]
@deep-man-yy I ran into what might be a bug. The app is having trouble writing the cropped file to the temporary directory in linux. The offending line is this: 
```
const inputPath = path.join(path.dirname(app.getPath('temp')), 'input.png')
```
`app.getPath('temp')` returns something like `'/tmp'` on linux, which gets converted to `'/'` by `path.dirname`. Is there a reason this function is used? I think  the following could replace this line:
```
const inputPath = path.join(app.getPath('temp'), 'input.png')
```
I think all other uses of `path.dirname` in that function should probably be removed too. Thoughts?

**Comment by deep-man-yy** [comment]
Holy shit, in fact **it is a bug**. This explains the problem that a user had.

The `path.dirname` is because initially the photo was going to be saved in a folder called `temp/` inside the program folder (next to `cli/` and `gui/`) and apparently forget to delete that line of code.

I am already working on the next version and this is no longer a problem as the photos will be saved elsewhere.

**Comment by wisp101** [comment]
Cool. I'll hold off on trying to get this to work on Linux until the next version comes out then.

**Comment by Miwwe** [comment]
@MatthewHKing you have autism if you use wine

**Comment by MatthewHKnight** [comment]
> @MatthewHKing you have autism if you use wine

This is coming from a kid who uses Windows.

**Comment by Miwwe** [comment]
> > @MatthewHKing you have autism if you use wine
> 
> This is coming from a kid who uses Windows.

Web fag retard, even though i'm younger than you i bet my ass can code better shit than you

**Comment by wisp101** [comment]
@Doctopus18 Looks like canary has Linux, mac, and windows versions. Have you tried testing those yet?

**Comment by wisp101** [comment]
@Doctopus18 Actually you don't have to test anymore. I did myself and opened #26 to fix the remaining problems. Still, maybe your distribution is different; the more testing the better :)

**Comment by wisp101** [comment]
A Linux version of canary has been confirmed to be working.
