### ISSUE TITLE
Poor or non existant error mesages

### ISSUE THREAD

**Issue by dpnde** [deep-man-yy/pepenude#8]
Attempted to build from source which is rather tedious. No real error messages and a lot of false positives when building. Unsure if I'm capturing all negative error cases.

Python2/3 is not very clear either and makes for a headache to install. Was able to get through all the node dependencies but still a difficult process.

If you do a botched install, the GUI just hangs indefinitely when trying to render--furthering offering poor indication of a successful build.

**Comment by deep-man-yy** [comment]
Yes, I'm sorry for the poor implementation for development, I did not test on a machine other than mine. Some users have reported missing libraries that are not installed with `install.bat`. More documentation and error messages will be implemented soon.
